name: Duels
main: com.meteordevelopments.duels.DuelsPlugin
version: @VERSION@
api-version: 1.21
folia-supported: true

author: Realized, DUMBO, Emmerich.
website: https://github.com/emmerichdev/Duels
description: A fork of https://github.com/dumbo-the-developer/Duels

dependencies:
  server:
    ASPaperPlugin:
      load: BEFORE
      required: true
      join-classpath: true
  optional:
    - DeluxeCombat
    - Essentials
    - PlaceholderAPI
    - Vault
    - WorldGuard

permissions:
  duels.*:
    children:
      duels.admin: true
  duels.admin:
    children:
      duels.default: true
      duels.stats.others: true
      duels.kits.*: true
      duels.teleport.bypass: true
      duels.spectate: true
      duels.spectate.anonymously: true
      duels.use.*: true
      duels.queue: true
  duels.default:
    children:
      duels.duel: true
      duels.stats: true
      duels.toggle: true
      duels.top: true
      duels.rank: true
  duels.duel:
    default: true
  duels.rank:
    default: true