name: Duels
main: com.meteordevelopments.duels.DuelsPlugin
version: @VERSION@
depend: [ASPaperPlugin]
softdepend: [DeluxeCombat, Essentials, PlaceholderAPI, Vault, WorldGuard]
api-version: 1.21

author: Realized, DUMBO, Emmerich.
website: https://github.com/emmerichdev/Duels
description: A fork of https://github.com/dumbo-the-developer/Duels

commands:
  duel:
    description: Send, accept, or deny a duel request.
    aliases: [ 1v1 ]
  party:
    description: Create, join, and duel parties.
    aliases: [ p, duelparty, dp ]
  queue:
    description: Join or leave a queue.
    aliases: [ q ]
  spectate:
    description: Spectate a duel.
    aliases: [ spec ]
  duels:
    description: Administrative command of Duels.
    aliases: [ ds ]
  rank:
    description: View your current rank information.
  testarena:
    description: Test an arena.
    aliases: [ test ]

permissions:
  duels.*:
    children:
      duels.admin: true
  duels.admin:
    children:
      duels.default: true
      duels.stats.others: true
      duels.kits.*: true
      duels.teleport.bypass: true
      duels.spectate: true
      duels.spectate.anonymously: true
      duels.use.*: true
      duels.queue: true
  duels.default:
    children:
      duels.duel: true
      duels.stats: true
      duels.toggle: true
      duels.top: true
      duels.rank: true
  duels.duel:
    default: true
  duels.rank:
    default: true

folia-supported: true